<?php

class Model_Tasks extends Model
{


    public function get_data($offest = 0, $limit = 3)
    {


        $page_num = isset($_REQUEST['p']) ? (int)$_REQUEST['p'] : 1;
        $sortBy = (isset($_REQUEST['sortBy'])) ? $_REQUEST['sortBy'] : 'task.id';
        $sortDir = (isset($_REQUEST['sortDir'])) ? $_REQUEST['sortDir'] : 'DESC';
        $offset = ($page_num - 1) * $limit;


        $dataarr = [];
        $total = $this->db->query('SELECT COUNT(*) FROM tasks')->fetchColumn();
        $q = "SELECT
                    task.id as task_id,
                    task.user_id,
                    task.pagetitle,
                    task.content, task.`status`, `user`.`user`, `user`.email
                    FROM tasks AS task INNER JOIN users AS `user` ON `user`.id = task.user_id
                    ORDER BY
                    $sortBy $sortDir
                    LIMIT $offset, $limit";
        $tasks = $this->db->query($q)->fetchAll();

        $pages = ceil($total / $limit);
        $dataarr['total'] = $total;
        $dataarr['offset'] = $offset;
        $dataarr['page'] = $page_num;
        $dataarr['pages'] = $pages;
        $dataarr['tasks'] = $tasks;
        return $dataarr;
    }

    public function set_data($data)
    {
        //parent::set_data($data); // TODO: Change the autogenerated stub

        $userID = $this->checkUserId($data['email']);
        $pagetitle = trim(htmlspecialchars($data['pagetitle']));
        $content = trim(htmlspecialchars($data['content']));

        //
        $this->db->query("INSERT INTO `tasks` (`user_id`, `pagetitle`, `content`, `status`) VALUES ('{$userID}', '{$pagetitle}', '{$content}', '1')");


    }

    public function checkUserId($email)
    {
        $check_user = $this->db->query("SELECT `id` FROM `users` WHERE `email` = '{$email}' LIMIT 0, 1");
        $check_Userid = $check_user->fetchColumn();
        if (!$check_Userid) {
            //createuser
            $user = explode("@", $email);
            $this->db->query("INSERT INTO `users` (`user`, `email`) VALUES ('{$user[0]}', '{$email}')");

            $check_Userid = ($this->db->lastInsertId());
        }
        return $check_Userid;


    }
}
